config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[show]
  resources :sports, only: %i[index show] do
    resources :pages, only: %i[index new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sports
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :weathers
  has_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sports, through: :categories
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :sport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!
  def index
    @sports = Sport.where(name: ["Trail", "VTT", "Running", "Snowboarding", "Traking"])
    
  end

  def show
    @sports = Sport.find(params[:id])
  end

  private

  def sports_params
    params.require(:sport).permit(:name, :distance, :adress, :description, :time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Undefined soon define</h1>

app/views/sports/index.html.erb
<h1>List circuit</h1>
<% if @sports.present? %>
  <ul>
    <% @sports.each do |sport| %>
    <%= link_to sport_path(sport) do %>
    <li>
      <p><%= sport.name %></p>
      <p><%= sport.distance %></p>
      <p><%= sport.time %></p>
      <p><%= sport.description %></p>
      <p><%= sport.address %></p>
      <p><%= sport.level %></p>
     </li>
    <% end %>
    <% end %>
 <% end %>

app/views/users/show.html.erb
<h1>Preferences</h1>
<h2>Choose a sport</h2>

<%= form_with url: sports_path, method: "get" do |f|  %>
<input type="checkbox" id="sport" name="running">
<label for="running">Running</label>
<input type="checkbox" id="sports" name="trail">
<label for="trail">Trail</label>
<input type="checkbox" id="sports" name="cycling">
<label for="cycling">Cycling</label>
<input type="checkbox" id="sports" name="vtt">
<label for="vtt">VTT</label>
<input type="checkbox" id="sports" name="snow">
<label for="snow">Snow Sports</label>
<input type="checkbox" id="sports" name="traking">
<label for="traking">Traking</label>
<input type="checkbox" id="sports" name="hiking">
<label for="hikinh">Hiking</label>
  <% end %>

<h2>Choose a level</h2>
<%= form_with url: sports_path, method: "get" do |f|  %>
<input type="checkbox" id="level" name="novice">
<label for="novice">Novice</label>
<input type="checkbox" id="level" name="intermediate">
<label for="intermediate">Intermediate</label>
<input type="checkbox" id="level" name="expert">
<label for="expert">Expert</label>
 <% end %>

<h2>Choose a frequence (at best)</h2>

<%= form_with url: sports_path, method: "get" do |f|  %>
<input type="checkbox" id="frequence" name="once">
<label for="once">Once a week</label>
<input type="checkbox" id="frequence" name="twice">
<label for="twice">Twice a week</label>
<input type="checkbox" id="frequence" name="three">
<label for="three">Three time a week</label>
 <% end %>



<h1>Nutrition preferences</h1>
<%= form_with url: sports_path, method: "get" do |f|  %>
<input type="checkbox" id="nutrition" name="vegetarian">
<label for="vegetarian">Vegetarian</label>
<input type="checkbox" id="nutrition" name="vegan">
<label for="vegan">Vegan</label>
<input type="checkbox" id="nutrition" name="gluten">
<label for="gluten">Gluten Free</label>
<input type="checkbox" id="nutrition" name="lactose">
<label for="lactose">Lactose Free</label>
<input type="checkbox" id="nutrition" name="fat">
<label for="fat">Low Fat</label>
<input type="checkbox" id="nutrition" name="sugar">
<label for="sugar">Low Sugar</label>
<input type="checkbox" id="nutrition" name="nothing">
<label for="nothing">Nothing to report</label>
<%= f.button "Let's check !", class:"button-link-to" %>
<% end  %>